/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile iPhone = new IPhone();
        Mobile android = new Android();

        iPhone.call("wow");
        iPhone.setName("iPhoneName");
        iPhone.setBrand("Apple");
        iPhone.setColor("Jet Black");
        iPhone.getInformation();

        android.call("uwu");
        android.setName("androidName");
        android.setBrand("Samsung");
        android.setColor("Black");
        android.getInformation();
    }
}
