/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile iPhone = new IPhone();
        Mobile android = new Android();

        iPhone.call("wow");
        android.call("uwu");
    }
}
